### ISSUE TITLE
Demoing Graphics Packages

### ISSUE THREAD

**Issue by psychemedia** [gap-system/try-gap-in-jupyter#2]
I discovered this repo via a series of tweets that also mentioned a couple of graphics packages that help to demonstrate some of the benefits of working in the Jupyter notebook environment.

It would be useful if the binder install supported by this repo also installed the [francy](gap-packages.github.io/francy/) and [Jupyterviz](https://nathancarter.github.io/jupyterviz/) packages and the demo notebook gave a small example of how they can be used to general graphic output?

**Comment by olexandr-konovalov** [comment]
@psychemedia thanks - actually, both Francy and JupyterViz can be launched on Binder in the same way like this repository. You need to click on Binder badges in their README files on GitHub:
- https://github.com/gap-packages/francy
- https://github.com/nathancarter/jupyterviz

(that's exactly how those images from that tweets were produced this morning).

Since this repo is based on GAP 4.10.0, both packages are already available here too - copying and pasting commands from their demo notebooks works fine. I will think of borrowing some examples from these packages to demonstrate all in one place.

**Comment by olexandr-konovalov** [comment]
@psychemedia I have added a short demo of a bar chart to the notebook contained in this repo, and also added references to jupyterviz and francy repos. Hope it looks now more informative, thanks for the suggestion!

**Comment by psychemedia** [comment]
Thanks for doing that...:-)

I should have checked the other repos properly (was being a bit lazy/unfocused...). Also, I didn't mean to detract from those projects, and their own custom demos; it just felt to me like this was a natural place to showcase Gap and some of the rich outputs that are afforded to it by the notebooks/Binderhub environment.

Thanks again...
